### ISSUE TITLE
Make READMEs

### ISSUE THREAD

**Issue by dylan-gonzalez** [MonashNovaRover/nova#59]
**CONTEXT**
There's a lot of code, and the people who understand it are all very busy -- ergo we need to write stuff down, so people who are new to the stack can get up to speed with relative ease. 
The format of these READMEs hasn't been defined, so we'll just slap some words together and see what sticks. Happy writing!

**TODO**
- [x] [pivot_drive_controller](https://github.com/MonashNovaRover/rover/tree/master/controllers/pivot_drive_controller) @dylan-gonzalez 
- [x] [blcmd_hardware](https://github.com/MonashNovaRover/rover/tree/master/hardware_interfaces/blcmd_hardware)
- [x] [nova_costmap_2d](https://github.com/MonashNovaRover/rover/tree/master/nav2_autonomous/nova_costmap_2d)
- [x] [nova_utils](https://github.com/MonashNovaRover/rover/tree/master/nova_utils)
- [x] [teleop_drive_joy](https://github.com/MonashNovaRover/rover/tree/master/teleop_drive_joy) @dylan-gonzalez

**Comment by dylan-gonzalez** [comment]
@ecthelion99 when you get a chance, take a look at my changes on [docs/pivot_drive_controller](https://github.com/MonashNovaRover/rover/tree/docs/pivot_drive_controller/controllers/pivot_drive_controller) and see if everything's correct?

**Comment by dylan-gonzalez** [comment]
I've done basic readmes for most of the packages now.
