### ISSUE TITLE
Fix teleop-drive-joy package

### ISSUE THREAD

**Issue by dylan-gonzalez** [MonashNovaRover/nova#65]
**CONTEXT**
`teleop_drive_joy` is to replace the old `drive_inputs` package to take input from the xbox controller to send drive commands to the rover. There are a few bugs with it that need to be fixed.

**TODO**
- [x] Document how to run the teleop-drive-joy package with the rover
- [ ] Document how to run the teleop-drive-joy package with a gazebo simulation
- [x] Discover/document issues with the rover dynamics when using the controller. Add to this todo list.
  - [x] Pivot controller
  - [x] Strafe controller
  - [x] Diff drive controller (less important)
- [x] Resolve issues with the controllers

**Comment by BaileyChessum** [comment]
What are the bugs?

**Comment by dylan-gonzalez** [comment]
I actually think this package is fine, but the problems are with `pivot_drive_controller`. I can't quite remember what the issues were, but you could probably see them if you spin up gazebo.

**Comment by BaileyChessum** [comment]
Run it with:

```bash
./result/bin/ros2 launch teleop_drive_joy teleop-launch.py joy_config:='xbox'
```

**Comment by BaileyChessum** [comment]
Running these commands (in different shells):

```bash
./result/bin/ros2 launch auto_bringup gazebo.launch.py
./result/bin/ros2 launch teleop_drive_joy teleop-launch.py joy_config:='xbox'
./result/bin/rqt
```

and running:

```bash
./result/bin/ros2 launch auto_bringup control.launch.py gazebo:='True'

# Then close the above, and run without gazebo:='True'
./result/bin/ros2 launch auto_bringup control.launch.py
```

yields:

![image](https://github.com/user-attachments/assets/5a88df9b-42a5-4f55-a9c2-fbfe43f6da84)

**Comment by BaileyChessum** [comment]
It seems that `drive_interfaces/msg/DriveInputStamped` messages, which contain a `drive_interfaces/msg/DriveInputStamped`, are being sent over the `/drive_input` topic. 

However, there is another topic called `/pivot_drive_controller/drove_input`, which accepts a `drive_interfaces/msg/DriveInputStamped`, which isn't having any messages published on it. The problem with `pivot_drive_controller` could be that it just isn't getting any input.

Could the problem be that the wrong topics are being used somewhere?

![image](https://github.com/user-attachments/assets/cacaf395-f7d5-494d-a7d7-1bd8a3fa25a7)

**Comment by BaileyChessum** [comment]
There are also some issues with being able to test this currently, as the auto_bringup gazebo launch files dont quite work. We need to set up out auto launch files and URDF to work with gazebo harmonic properly first.

#95

**Comment by dylan-gonzalez** [comment]
Hey sorry just saw your comments here. From memory I set it up so that `pivot_drive_controller` can accept either stamped or unstamped messages - you just have to enable/disable the parameter. I have tested teleop-drive-joy with the controller and it works fine - 'fine' as in it can control the rover. There are some issues with the rover dynamics when using the controller that I think boil down to issues with the controller itself, rather than teleop-drive-joy.

**Comment by KABILAN235** [comment]
@BaileyChessum What's the Status with this task?

**Comment by BaileyChessum** [comment]
@KABILAN235 I haven't made any progress since posting here, I've been focusing on getting people up and running with ros2_control. Feel free to join software meeting tonight, I raise this as a discussion point.

**Comment by vic-bart** [comment]
@BaileyChessum Status update on teleop-drive-joy!
@KABILAN235 tested it out on his laptop and couldn't find any issues. It now needs to be tested on the rover.

**Comment by KABILAN235** [comment]
@BaileyChessum Teleop Drive Joy works good with the Joystick and does produce the expected `Twist` or `DriveInput`. Since we can't really test this on sim, it's really hard to pinpoint where the problem lies. A "On the Rover" Test would clear up a bunch of stuff here
