### ISSUE TITLE
Move github actions for the mono-repo

### ISSUE THREAD

**Issue by BaileyChessum** [MonashNovaRover/nova#94]
Github actions made for nixfiles, rover and nova-gui are now hidden away in subdirectories of the mono-repo, essentially making them inactive. This task is to migrate the github actions to the monorepo:

**TODO**

- [ ] nixfiles actions migrated
- [x] rover actions migrated
- [x] nova-gui actions migrated

  
  Tags for Notion Integration:
  tag:ci/cd

**Comment by FelicityMatt** [comment]
no github actions for nova-gui and rover, only one for nixfiles that doesn't seems to have worked for a while

**Comment by FelicityMatt** [comment]
@hacker1024 is this workflow worth porting to the mono-repo at some point? looks like it's been failing for a while.
https://github.com/MonashNovaRover/nixfiles/blob/master/.github/workflows/update.yml
